// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplication.Entity.Models
{
    public partial class JobApplicationTable
    {
        public int Applicant_ID { get; set; }
        public string Applicant_Name { get; set; }
        public string Applicant_Gender { get; set; }
        public int Applicant_Age { get; set; }
        public string Applicant_Email { get; set; }
        public string Applicant_Location { get; set; }
        public string Applicant_Resume { get; set; }
        public string Applicant_FullName { get; set; }
        public int Applicant_Xth_Mark { get; set; }
        public int Applicant_XIIth_Mark { get; set; }
        public int Applicant_CGPA { get; set; }
        public string Applicant_Interest { get; set; }
        public string Applicant_Skills { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }
    }
}